# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Building Software That Doesn't Suck
email: sean@gneoxsolutions.com
description: > # this means to ignore newlines until "baseurl:"
  Findings and thoughts from a man frustrated with a world that insists on doing the wrong things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.gneoxsolutions.com" # the base hostname & protocol for your site
twitter_username: SeanFreitag
github_username:  cowboygneox

# Build settings
markdown: kramdown